---
- hosts: all
  become: yes

  vars_files:
    - aws-plays-vars.yml

  roles:
    - { role: ansible-role-base }
    - { role: ansible-role-postfix }
    - { role: ansible-role-users }
    - role: geerlingguy.ntp
      ntp_enabled: true
      ntp_timezone: "{{ base_timezone }}"
      ntp_manage_config: false
    - { role: angstwad.docker_ubuntu }

   tasks:
     - name: create server volumes
       filesystem: fstype=ext4 dev=/dev/xvdb
     - name: mount server volumes
       mount:
         name: /opt
         src: /dev/xvdb
         fstype: ext4
         state: mounted
