---
- hosts: all
  become: yes

  vars_files:
    - vars.yml

  roles:
    - { role: ansible-role-base }
    - { role: ansible-role-postfix }
    - { role: ansible-role-users }
    - role: geerlingguy.ntp
      ntp_enabled: true
      ntp_timezone: "{{ base_timezone }}"
      ntp_manage_config: false
    - { role: angstwad.docker_ubuntu }
